/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Edge: typeof import('./src/components/Edge.vue')['default']
    EdgeBezierCurve: typeof import('./src/components/EdgeBezierCurve.vue')['default']
    EdgeEndHandle: typeof import('./src/components/EdgeEndHandle.vue')['default']
    Flow: typeof import('./src/components/Flow.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Node: typeof import('./src/components/Node.vue')['default']
    NodeHandle: typeof import('./src/components/NodeHandle.vue')['default']
    NodePort: typeof import('./src/components/NodePort.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
